## Programming Assignment 5
---
**Author:** Morgan Hardin  
**Version:** 1.0  
**Semester:** Spring 2024 

This *notebook* contains my solution(s) to **Programming Assignment 5**

- Problem 1: Language Translator
- Problem 2: Translating Morse Code
- Problem 3: Comparing Minors / Majors
- Problem 4: Working with NumPy

### Importing Libraries

In [1]:
import numpy as np

### Language Translator

In [2]:
d_EtoS = {
    "hello": "hola",
    "cat": "gato",
    "dog": "perro",
    "book": "libro",
    "bed": "cama",
    "house": "casa",
    "car": "coche",
    "friend": "amigo",
    "teacher": "maestro",
    "apple": "manzana",
    "cheese": "queso",
    "bread": "pan",
    "milk": "leche",
    "red": "rojo",
    "green": "verde", 
    "ball": "pelota",
    "beach": "playa",
    "tiger": "tigre",
    "computer": "computadora",
    "backpack": "mochila"
}
answer = input("Enter a word to translate from English to Spanish (Enter Q to Stop): ")
while (answer != "Q"):
    if answer in d_EtoS.keys():
        print(f"The Spanish word for {answer} is {d_EtoS[answer]}.")
    else:
        print(f"The Spanish word for {answer} is not in this dictionary.")
    answer = input("Enter a word to translate from English to Spanish (Enter Q to Stop): ")

Enter a word to translate from English to Spanish (Enter Q to Stop):  car


The Spanish word for car is coche.


Enter a word to translate from English to Spanish (Enter Q to Stop):  yes


The Spanish word for yes is not in this dictionary.


Enter a word to translate from English to Spanish (Enter Q to Stop):  Q


### Translating Morse Code

In [3]:
d_MC = {
    "A": ".-", "B": "-...", "C": "-.-.", "D": "-..", "E": ".", "F": "..-.",
    "G": "--.", "H": "....", "I": "..", "J": ".---", "K": "-.-", "L": ".-..",
    "M": "--", "N": "-.", "O": "---", "P": ".--.", "Q": "--.-", "R": ".-.",
    "S": "...", "T": "-", "U": "..-", "V": "...-", "W": ".--", "X": "-..-",
    "Y": "-.--", "Z": "--..", "0": "-----", "1": ".----", "2": "..---",
    "3": "...--", "4": "....-", "5": ".....", "6": "-....", "7": "--...",
    "8": "---..", "9": "----.", " ": " "
}

In [4]:
def translate_mc(phrase):
    split = [*phrase]
    for char in split:
        if char in d_MC.keys():
            print(d_MC[char], end = "")

In [5]:
answer = input("Enter a phrase in all caps to translate to Morse Code (Enter q to Stop): ")
while (answer != "q"):
    translate_mc(answer)
    answer = input("Enter a phrase in all caps to translate to Morse Code (Enter q to Stop): ")

Enter a phrase in all caps to translate to Morse Code (Enter q to Stop):  HELLO MISTER


......-...-..--- --.....-..-.

Enter a phrase in all caps to translate to Morse Code (Enter q to Stop):  q


### Comparing Minors / Majors

In [6]:
CS_Minor = {"CS 130", "CS 131", "CS 215", "CS 310", "CS 330", "CS 415"}
BUAD_Minor = {"BUSA 103", "BUSA 203", "BUSA 301", "BUSA 305", "ACCT 101", 
              "ECON 110", "FINA 315", "MATH 117"}
BUAN_Minor = {"BUSA 103", "BUSA 245", "BUSA 346", "CS 150", "DS 160", 
              "DS 300", "MATH 117", "MATH 205"}
DS_Major = {"BUSA 103", "BUSA 245", "BUSA 346", "CS 150", "DS 160", 
            "DS 300", "DS 450", "MATH 117", "MATH 205", "MATH 215", 
            "MATH 430", "ECON 110", "ECON 111", "ECON 410", "DS 444"}

In [7]:
# if a student minors in business administration and business analytics,
# what courses overlap?

print("Businessness Administration and Business Analytics Minors Course Overlaps: ")
print(BUAD_Minor & BUAN_Minor)

# answer: BUSA 103 and MATH 117 overlap between the two minors.

Businessness Administration and Business Analytics Minors Course Overlaps: 
{'BUSA 103', 'MATH 117'}


In [8]:
# if a student minors in business administration and computer science,
# get a list of all the courses they would have to take.

print("All of the courses they would have to take are: ")
print(sorted(BUAD_Minor | CS_Minor))

# answer: all of the courses they would have to take are: ACCT 101,
# BUSA 103, BUSA 203, BUSA 301, BUSA 305, CS 130, CS 131, CS 215, 
# CS 310, CS 330, CS 415, ECON 110, FINA 315, MATH 217.

All of the courses they would have to take are: 
['ACCT 101', 'BUSA 103', 'BUSA 203', 'BUSA 301', 'BUSA 305', 'CS 130', 'CS 131', 'CS 215', 'CS 310', 'CS 330', 'CS 415', 'ECON 110', 'FINA 315', 'MATH 117']


In [9]:
# find a list of courses that are in the business administration minor
# but are not in the business analytics minor.

print("Courses in Business Administration Minor but not Business Analytics Minor: ")
print(sorted(BUAD_Minor - BUAN_Minor))

# answer: all of the courses in the business administration minor
# but not in the business analytics minor are: ACCT 101. BUSA 203, 
# BUSA 301, BUSA 305, ECON 110, and FINA 315.

Courses in Business Administration Minor but not Business Analytics Minor: 
['ACCT 101', 'BUSA 203', 'BUSA 301', 'BUSA 305', 'ECON 110', 'FINA 315']


In [10]:
# verify that there are no overlapping courses between the computer
# science minor and the data science major.

print("Shared courses between CS Minor and DS Major: ")
print(sorted(CS_Minor & DS_Major))

# answer: this shows an empty set, meaning that there is no overlap.

Shared courses between CS Minor and DS Major: 
[]


In [11]:
# verify that the business analytics minor is completely subsumed 
# by the data science major.

print("Business Analytics Minor subsumed by DS Major: ")
print(sorted(BUAN_Minor))
print(sorted(BUAN_Minor & DS_Major))

# answer: this shows that both the business analytics minor and ds
# major both consists of the same classes and that the business 
# analytics minor is subsumed by the ds major

Business Analytics Minor subsumed by DS Major: 
['BUSA 103', 'BUSA 245', 'BUSA 346', 'CS 150', 'DS 160', 'DS 300', 'MATH 117', 'MATH 205']
['BUSA 103', 'BUSA 245', 'BUSA 346', 'CS 150', 'DS 160', 'DS 300', 'MATH 117', 'MATH 205']


### Working with NumPy

In [12]:
A = np.random.randint(0, 21, size = (5, 5))
B = np.random.randint(0, 21, size = (5, 5))

In [13]:
A

array([[18,  8, 10,  5, 11],
       [15,  6, 18, 14,  6],
       [ 5,  2, 18, 18, 12],
       [ 0, 18,  0, 10, 19],
       [17,  3,  7, 19, 13]])

In [14]:
B

array([[13, 10,  2, 18,  7],
       [13, 15, 18,  2,  5],
       [14,  3,  3,  5, 10],
       [ 1,  1, 13,  0,  6],
       [19,  6, 20,  3, 10]])

In [15]:
# dot product
dot_product = np.dot(A, B)
print("The dot product is: ")
dot_product

The dot product is: 


array([[692, 401, 495, 423, 406],
       [653, 344, 494, 390, 459],
       [589, 224, 574, 220, 453],
       [605, 394, 834,  93, 340],
       [624, 333, 616, 386, 448]])

In [16]:
# determinant of A
determinant_A = np.linalg.det(A)
print("The determinant is: ")
determinant_A

The determinant is: 


-778736.0000000008

In [17]:
# determinant of B
determinant_B = np.linalg.det(B)
print("The determinant is: ")
determinant_B

The determinant is: 


-245316.00000000003

In [18]:
# inverse of A
inverse_A = np.linalg.inv(A)
print("The inverse is: ")
inverse_A

The inverse is: 


array([[ 0.03028497,  0.00882969, -0.03729634, -0.01724846,  0.02993569],
       [-0.0390068 ,  0.09904127, -0.06712544,  0.05172741, -0.02634526],
       [ 0.02902139,  0.01253185,  0.04872383, -0.01313667, -0.05611658],
       [-0.08894414,  0.05632718, -0.02733661,  0.01503976,  0.05251587],
       [ 0.08376651, -0.12347445,  0.07798021, -0.004289  , -0.00268127]])

In [19]:
# inverse of B
inverse_B = np.linalg.inv(B)
print("The inverse is: ")
inverse_B

The inverse is: 


array([[-0.00957133, -0.01864534, -0.00780626, -0.09839962,  0.08286863],
       [-0.00934305,  0.10360515,  0.05583818,  0.00829135, -0.10607543],
       [ 0.01343573, -0.01897145, -0.07549854,  0.02952518,  0.05786414],
       [ 0.07626082, -0.05246295, -0.07749596,  0.01740204,  0.03990363],
       [-0.02595836,  0.02694484,  0.15557485,  0.11771348, -0.12150451]])

In [20]:
# 1D array: 20 evenly spaced from 0 to 1
C = np.linspace(0, 1, num = 20)
C

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [21]:
# 1D array: 20 evenly spaced from 0 to 1
D = np.linspace(1, 2, num = 20)
D

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [22]:
# concatenate arrays C and D
CD = np.hstack((C, D))
CD

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ,
       1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [23]:
# reshaping array CD into 2D array of (10, 4)
CD_reshape = CD.reshape(10, 4)
CD_reshape

array([[0.        , 0.05263158, 0.10526316, 0.15789474],
       [0.21052632, 0.26315789, 0.31578947, 0.36842105],
       [0.42105263, 0.47368421, 0.52631579, 0.57894737],
       [0.63157895, 0.68421053, 0.73684211, 0.78947368],
       [0.84210526, 0.89473684, 0.94736842, 1.        ],
       [1.        , 1.05263158, 1.10526316, 1.15789474],
       [1.21052632, 1.26315789, 1.31578947, 1.36842105],
       [1.42105263, 1.47368421, 1.52631579, 1.57894737],
       [1.63157895, 1.68421053, 1.73684211, 1.78947368],
       [1.84210526, 1.89473684, 1.94736842, 2.        ]])